### ISSUE TITLE
How to run server on `Java21+` (Cleanroom)?

### ISSUE THREAD

**Issue by Candy-sky** [Krutoy242/Enigmatica2Expert-Extended#500]
Cleanroom is a high - performance modern Forge branch. Or can I try to port it myself?

**Comment by Krutoy242** [comment]
I dont get it. Do you want to launch E2EE server on Java 21? How can i help?

**Comment by Candy-sky** [comment]
I'm sorry for not being clear enough. Could you please provide an official server version based on Cleanroom? It would be great if it could be offered as an additional option, similar to how different server versions are available, to give us a better - performing alternative.

**Comment by Candy-sky** [comment]
Well, thanks for your patience! I don't know if it sounds weird, but I'm using a translation software, sorry

**Comment by Yesquero** [comment]
Turns out it's pretty easy to  modify `server-setup-config.yaml` provided with the modpack to use Cleanroom, you only need to change `loaderVersion`, `installerUrl`, `startFile`, potentially `forcedJavaPath` and clean up java arguments.

I've used this for a while now and haven't noticed any issues with installing or running the modpack, just be mindful with loader and modpack versions when editing the config file. Also java args im using are probably not optimal. 

<details>
<summary>Here is the full server config file, don't mind min and max ram config</summary>

```yaml
# Version of the specs, only for internal usage if this format should ever change drastically
_specver: 2

# modpack related settings, changes the supposed to change the visual appearance of the launcher
modpack:
  # Name of the mod pack, that is displayed in various places where it fits
  name: Enigmatica 2 Expert Extended

  # Description
  description: Continuation of E2E, Cleanroom loader

# settings regarding the installation of the modpack
install:
  # version of minecraft, needs the exact version
  mcVersion: 1.12.2

  # exact version of forge or fabric that is supposed to be used
  # if this value is a null value so ( ~, null, or "" ) then the version from the mod pack is going to be used
  loaderVersion: 0.3.4-alpha

  # If a custom installer is supposed to used, specify the url here: (Otherwise put "", ~ or null here)
  # supports variables: {{@loaderversion@}} and {{@mcversion@}}
  # For forge: "http://files.minecraftforge.net/maven/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/forge-{{@mcversion@}}-{{@loaderversion@}}-installer.jar"
  # For Fabric: "https://maven.fabricmc.net/net/fabricmc/fabric-installer/{{@loaderversion@}}/fabric-installer-{{@loaderversion@}}.jar"
  installerUrl: 'https://github.com/CleanroomMC/Cleanroom/releases/download/{{@loaderversion@}}/cleanroom-{{@loaderversion@}}-installer.jar'

  # Installer Arguments
  # These Arguments have to be passed to the installer
  #
  # For Fabric:
  # installerArguments:
  #   - "server"
  #   - "-downloadMinecraft"
  #
  # For Fabric if you want to use snapshot version:
  # installerArguments:
  #   - "server"
  #   - "-mcversion 20w07a"
  #   - "-downloadMinecraft"
  #
  # For Forge:
  # installerArguments:
  #   - "--installServer"
  installerArguments:
    - --installServer

  # Link to where the file where the modpack can be distributed
  # This supports loading from local files as well for most pack types if there is file://{PathToFile} in the beginning
  modpackUrl: https://github.com/Krutoy242/Enigmatica2Expert-Extended/releases/download/v1.60.4/E2E-Extended-v1.60.4.zip

  # This is used to specify in which format the modpack is distributed, the server launcher has to handle each individually if their format differs
  # current supported formats:
  # - curseforge or curse
  # - curseid
  # - zip or zipfile
  modpackFormat: curse

  # Settings which are specific to the format used, might not be needed in some casese
  formatSpecific:
    # optional paramenter used for curse to specify a whole project to ignore (mostly if it is client side only)
    ignoreProject:
      - 79287 # Waila Harvestability
      - 222378 # MineMenu
      - 225928 # Custom Backgrounds
      - 226406 # Custom Main Menu
      - 226447 # Resource Loader
      - 231453 # ChatFlow
      - 236484 # Chunk Animator
      - 237701 # ReAuth
      - 238372 # Neat
      - 238891 # Dynamic Surroundings
      - 240630 # Just Enough Resources (JER)
      - 243478 # More Overlays
      - 245733 # ToroHealth Damage Indicators
      - 250398 # Controlling
      - 262366 # Keyboard Wizard
      - 267602 # ConnectedTexturesMod
      - 267939 # Just Enough HarvestCraft (JEHC)
      - 272515 # Better Advancements
      - 280294 # FPS Reducer
      - 285492 # Thaumic JEI
      - 285742 # Smooth Font
      - 291727 # Just Enough Petroleum
      - 293496 # OldJavaWarning
      - 295736 # MemoryTester
      - 297038 # CraftPresence
      - 297363 # Biome Border Viewer
      - 299080 # Proportional Destruction Particles
      - 303122 # Just Enough Throwing In Fluids (JETIF)
      - 306549 # Tips
      - 308240 # Cherished Worlds
      - 310560 # Grid
      - 311927 # Nimble (Forge)
      - 313816 # Armor Toughness Bar
      - 314002 # Overloaded Armor Bar
      - 316304 # Loot Capacitor Tooltips
      - 319656 # ScalingGUIs
      - 327048 # IconExporter
      - 403303 # Potion Descriptions (Forge)
      - 408853 # Particle Culling
      - 409087 # Entity Culling
      - 417557 # BilingualName
      - 438451 # Precision Mining
      - 446253 # Better Biome Blend
      - 454215 # Just Enough Drags
      - 461660 # Mouse Tweaks Unofficial
      - 502649 # Mini Effects
      - 513769 # Item Borders [Forge]
      - 521590 # Item Highlighter
      - 532127 # Legendary Tooltips
      - 616190 # JEI Utilities
      - 624967 # RenderLib
      - 782070 # Startup Timer
      - 848933 # Hit Indication
      - 874067 # Valkyrie
      - 940521 # Just Enough Magiculture
      - 1056812 # UniLib
      - 1073925 # Rather Enough Immersive Multiblocks
      - 1081085 # MiniEffects-Legacy Extended Life
      - 1085598 # JEI Area Fixer
      - 1121489 # AE2 Crafting Tree - Legacy
      - 1132293 # Backpack Display
      - 1147522 # Backpack Opener
      - 1234162 # Lumenized

    # The base path where the server should be installed to, ~ for current path
  baseInstallPath: ~

  # a list of files which are supposed to be ignored when installing it from the client files
  # this can either use regex or glob {default glob: https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-}
  # specify with regex:.... or glob:.... if you want to force a matching type
  ignoreFiles:
    - config/thaumicjei_itemstack_aspects.json
    - minemenu
    - resourcepacks
    - resources
    - schematics

    # often a server needs more files, which are nearly useless on the client, such as tickprofiler
    # This is a list of files, each ' - ' is a new file:
    # url is the directlink to the file, destination is the path to where the file should be copied to
  additionalFiles:
    ~
    # - url: https://media.forgecdn.net/files/2844/278/restrictedportals-1.15-1.0.jar
    #  destination: mods/restrictedportals-1.15-1.0.jar
    # - url: https://media.forgecdn.net/files/2874/966/Morpheus-1.15.2-4.2.46.jar
    #  destination: mods/Morpheus-1.15.2-4.2.46.jar
    # - url: https://media.forgecdn.net/files/2876/89/spark-forge.jar
    #  destination: mods/spark-forge.jar

    # For often there are config which the user wants to change, here is the place to put the local path to configs, jars or whatever
    # You can copy files or folders
  localFiles:
  # - from: setup/modpack-download.zip
  #  to: setup/test/modpack-download-copied.zip
  # - from: setup/AOF 2/.minecraft
  #  to: setup/.

  # This makes the program check the folder for whether it is supposed to use the
  checkFolder: true

  # Whether to install the Loader (Forge or Fabric) or not, should always be true/true unless you only want to install the pack
  installLoader: true

  # Sponge bootstrapper jar URL
  # Only needed if you have spongefix enabled
  spongeBootstrapper: https://github.com/simon816/SpongeBootstrap/releases/download/v0.7.1/SpongeBootstrap-0.7.1.jar

  # Time in seconds before the connection attempt to any webservice like forge/curseforge times out
  # Only increase this timer if you have problems
  connectTimeout: 30

  # Time in seconds before the read attempt to any webservice like forge/curseforge times out
  # Only increase this timer if you have problems
  readTimeout: 30

# settings regarding the launching of the pack
launch:
  # applies the launch wrapper to fix sponge for a few mods
  spongefix: false

  # Use a RAMDisk for the world folder
  # case-sensitive; use only lowercase `true` or `false`
  # NOTE: The server must have run once fully before switching to `true`!
  ramDisk: false

  # checks with the help of a few unrelated server whether the server is online
  checkOffline: false

  # specifies the max amount of ram the server is supposed to launch with
  maxRam: 7G

  # specifies the min amount of ram the server is supposed to launch with
  minRam: 7G

  # specifies whether the server is supposed to auto restart after crash
  autoRestart: false

  # after a given amount of crashes in a given time the server will stop auto restarting
  crashLimit: 10

  # Time a crash should be still accounted for in the {crashLimit}
  # syntax is either [number]h or [number]min or [number]s
  crashTimer: 5min

  # Arguments that need to go before the 'java' argument, something like linux niceness
  # This is only a string, not a list.
  preJavaArgs: ~

  # Start File Name, variables: {{@loaderversion@}} and {{@mcversion@}}
  # This has to be the name the installer spits out
  # For Forge 1.12-: "forge-{{@mcversion@}}-{{@loaderversion@}}-universal.jar"
  # For Forge 1.13+: "forge-{{@mcversion@}}-{{@loaderversion@}}.jar"
  # For Fabric: "fabric-server-launch.jar"
  startFile: 'cleanroom-{{@loaderversion@}}.jar'

  # This is the command how the server is supposed to be started
  # For <1.16 it should be
  #  - "-jar"
  #  - "{{@startFile@}}"
  #  - "nogui"
  # For >=1.17 it should be
  # - "@libraries/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/{{@os@}}_args.txt"
  # - "nogui"
  startCommand:
    - -jar
    - '{{@startFile@}}'
    - nogui

    # In case you have multiple javas installed you can add a absolute path to it here
    # if the value is "", null, or ~ then 'java' from PATH is going to be used
    # Example: "\"C:/Program Files/Java/jre1.8.0_201/bin/java.exe\""
  forcedJavaPath: "/opt/java/zulu-java-24/bin/java"

  # Java args that are supposed to be used when the server launches
  # keep in mind java args often need ' - ' in front of it to work, use clarifying parentheses to make sure it uses it correctly
  # reference: https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
  # tested on Java 8 and 11
  javaArgs:
    - '-XX:+UnlockExperimentalVMOptions'
    - '-XX:+UseZGC'
    - '-XX:+UseCompactObjectHeaders'
    - '-XX:+DisableExplicitGC'
    - '-XX:+AlwaysPreTouch'
    - '-XX:SurvivorRatio=32'
    - '-XX:+PerfDisableSharedMem'
    - '-XX:MaxTenuringThreshold=1'
    - -Dfml.readTimeout=180 # servertimeout
    - -Dfml.queryResult=confirm # auto /fmlconfirm
    - --add-opens=java.base/sun.security.util=ALL-UNNAMED # java16+ support
    - --add-opens=java.base/java.util.jar=ALL-UNNAMED # java16+ support
    - '-XX:+IgnoreUnrecognizedVMOptions' # java16+ support

```

</details>

<details>
<summary>Diff between modified config file and default one, again don't mind min and max ram config</summary>

```
10c10
<   description: Continuation of E2E, Cleanroom loader
---
>   description: Continuation of E2E
19c19
<   loaderVersion: 0.3.4-alpha
---
>   loaderVersion: ~
25c25
<   installerUrl: 'https://github.com/CleanroomMC/Cleanroom/releases/download/{{@loaderversion@}}/cleanroom-{{@loaderversion@}}-installer.jar'
---
>   installerUrl: 'https://files.minecraftforge.net/maven/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/forge-{{@mcversion@}}-{{@loaderversion@}}-installer.jar'
191c191
<   maxRam: 7G
---
>   maxRam: 5G
194c194
<   minRam: 7G
---
>   minRam: 2G
215c215
<   startFile: 'cleanroom-{{@loaderversion@}}.jar'
---
>   startFile: 'forge-{{@mcversion@}}-{{@loaderversion@}}.jar'
233c233
<   forcedJavaPath: "/opt/java/zulu-java-24/bin/java"
---
>   forcedJavaPath: ~
239a240,242
>     - '-XX:+UseG1GC'
>     - '-XX:+ParallelRefProcEnabled'
>     - '-XX:MaxGCPauseMillis=200'
241,242d243
<     - '-XX:+UseZGC'
<     - '-XX:+UseCompactObjectHeaders'
244a246,254
>     - '-XX:G1NewSizePercent=30'
>     - '-XX:G1MaxNewSizePercent=40'
>     - '-XX:G1HeapRegionSize=8M'
>     - '-XX:G1ReservePercent=20'
>     - '-XX:G1HeapWastePercent=5'
>     - '-XX:G1MixedGCCountTarget=4'
>     - '-XX:InitiatingHeapOccupancyPercent=15'
>     - '-XX:G1MixedGCLiveThresholdPercent=90'
>     - '-XX:G1RSetUpdatingPauseTimePercent=5'
247a258,259
>     - '-Dusing.aikars.flags=https://mcflags.emc.gs'
>     - -Daikars.new.flags=true
```

</details>

As for benefits of using Cleanrrom server ( besides faster startup times ), using Java 24 and [Compact Object Headers](https://openjdk.org/jeps/450) reduces RAM usage. Also it _feels_ like loading new chunks is faster with newer java versions but i haven't measured anything so idk.

One thing to keep in mind is that while Cleanroom clients can join Forge servers, Forge clients **cannot** join Cleanroom servers.
